engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      universal-selector:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - src/**
  - asset/**
  - tests/**
