engines:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      universal-selector:
        enabled: false
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
    - 110a6bbdc7e94eb4a86542674654e023
    - 68e7b9449b2a6da0aa1c847020ce1f7b
ratings:
  paths:
  - src/**
  - asset/**
  - tests/**
